# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  # pestphp
  - pest
  # PHPstan
  - code-quality
  # SAST scanner
  - test
  - convert
  - release-fetch-version
  - release-build
  - release
  - badges
  - deploy

cache:
  key: build_cache
  paths:
  - vendor/
  - composer.lock
variables:
  DOCKER_IMAGE: "registry.gitlab.com/jfheinrich-eu/docker/nodejs:latest"
  DOCKER_PY_IMAGE: "python:latest"
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp, vendor, node_modules"

include:
- template: Jobs/SAST.gitlab-ci.yml
- local: gitlab-ci/build.yml
- local: gitlab-ci/tests.yml
- local: gitlab-ci/semver.yml
- local: gitlab-ci/sast-report.yml
- local: gitlab-ci/badges.yml
- local: gitlab-ci/deploy.yml
- template: Security/Secret-Detection.gitlab-ci.yml
