name: laravel-make-commands
recipe: lemp
config:
  via: nginx
  webroot: public
  php: 8.1
  composer_version: 2-latest
  xdebug: true

services:
  appserver:
    build_as_root:
      - ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
      - echo "Europe/Berlin" > /etc/timezone
