---
version: 2
updates:
  - package-ecosystem: composer
    vulnerability-alerts:
      enabled: true
      confidential: true
      assignees:
        - j.f.heinrich
    directory: /
    schedule:
      interval: daily
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
