build:
  image: ${DOCKER_IMAGE}
  stage: build
  tags:
    - build
  script:
    - composer install --no-progress --no-scripts
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor/
      - node_modules/
      - package.json
      - package-lock.json
      - composer.lock
