testbench:
  image: ${DOCKER_IMAGE}
  stage: testbench
  tags:
    - tests
  script:
    - composer test:coverage
  coverage: /^\s*Total:\s*\d+\.\d+?\s*\%\s*$/
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor/
      - composer.lock

code-quality:
  image: ${DOCKER_IMAGE}
  stage: code-quality
  tags:
    - tests
  script:
    - composer check
    - composer static
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor/
      - composer.lock
