build_badges:
  stage: triggers
  trigger:
    include: gitlab-ci/badges.yml
  rules:
    - if: $CI_COMMIT_TAG

deployment:
  stage: triggers
  trigger:
    include: gitlab-ci/deploy.yml
  rules:
    - if: $CI_COMMIT_TAG